// Generated by Wrangler by running `wrangler types`

interface Env {
	CREATIVE_BASE_URL: "https://localhost:5175/resources/creatives/";
	VITE_CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_WEBHOOK_SECRET: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	R2: R2Bucket;
}
