#:schema node_modules/wrangler/config-schema.json
name = "remix-cloudflare-workers-template"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-09-26"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "video-ad-network"
database_id = "ad4c0de9-dc9d-44b1-b2c2-e7f343cf2841"


[build]
command = "npm run build"
