#:schema node_modules/wrangler/config-schema.json
name = "ui"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-26"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'video-ad-network'

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "pnpm run build"

