packages:
  - ./apps/*
  - ./packages/*
catalog:
  "@biomejs/biome": 1.9.2
  "@cloudflare/workers-types": 4.20240925.0
  "@google-cloud/bigquery": 7.9.1
  "@hono/node-server": 1.13.1
  "@hono/vite-build": 1.1.0
  "@hono/vite-dev-server": 0.16.0
  "@types/node": 20.11.17
  biome: 0.3.3
  fast-xml-parser: 4.5.0
  hono: 4.6.3
  npm-run-all: 4.1.5
  turbo: 2.1.3
  typescript: 5.6.2
  vite: 5.4.8
  vitest: 2.1.2
  wrangler: 3.78.12
