packages:
  - ./apps/*
  - ./packages/*

catalog:
  '@biomejs/biome': 2.3.8
  '@clerk/react-router': 2.3.2
  '@cloudflare/workers-types': 4.20251205.0
  '@date-fns/tz': 1.4.1
  '@date-fns/utc': 2.1.1
  '@hono/node-server': 1.13.7
  '@hono/vite-build': 1.8.0
  '@hono/vite-dev-server': 0.23.0
  '@libsql/kysely-libsql': 0.4.1
  '@radix-ui/react-accordion': 1.2.2
  '@radix-ui/react-alert-dialog': 1.1.4
  '@radix-ui/react-aspect-ratio': 1.1.1
  '@radix-ui/react-avatar': 1.1.2
  '@radix-ui/react-checkbox': 1.1.3
  '@radix-ui/react-dialog': 1.1.4
  '@radix-ui/react-dropdown-menu': 2.1.4
  '@radix-ui/react-label': 2.1.1
  '@radix-ui/react-popover': 1.1.4
  '@radix-ui/react-select': 2.1.4
  '@radix-ui/react-separator': 1.1.1
  '@radix-ui/react-slot': 1.1.1
  '@radix-ui/react-switch': 1.1.2
  '@radix-ui/react-tabs': 1.1.2
  '@radix-ui/react-toggle': 1.1.1
  '@radix-ui/react-tooltip': 1.1.6
  '@react-router/cloudflare': 7.10.1
  '@react-router/dev': 7.10.1
  '@react-router/remix-routes-option-adapter': 7.10.1
  '@types/node': 24.10.1
  '@types/nprogress': 0.2.3
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@typescript-eslint/eslint-plugin': 6.7.4
  '@typescript-eslint/parser': 6.7.4
  autoprefixer: 10.4.22
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  concurrently: 9.2.1
  date-fns: 4.1.0
  dotenv: 17.2.3
  fast-xml-parser: 5.3.2
  hono: 4.10.7
  isbot: 5.1.32
  kysely: 0.28.8
  lucide-react: 0.556.0
  next-themes: 0.4.6
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.5.6
  prettier: 3.7.4
  prettier-plugin-organize-imports: 4.3.0
  prettier-plugin-tailwindcss: 0.7.2
  prisma: 7.1.0
  prisma-kysely: 2.2.1
  react: 19.2.1
  react-dom: 19.2.1
  react-router: 7.10.1
  react-twc: 1.5.1
  recharts: 3.5.1
  remix-flat-routes: 0.8.5
  sonner: 2.0.7
  tailwind-merge: 3.4.0
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  tsx: 4.21.0
  turbo: 2.6.3
  typescript: 5.9.3
  vaul: 1.1.2
  vite: 7.2.6
  vite-tsconfig-paths: 5.1.4
  vitest: 4.0.15
  wrangler: 4.53.0
  zx: 8.8.5

ignoredBuiltDependencies:
  - prisma

onlyBuiltDependencies:
  - '@clerk/shared'
  - b
  - d
  - e
  - i
  - l
  - s
  - u
