packages:
  - ./apps/*
  - ./packages/*
catalog:
  '@biomejs/biome': 1.9.4
  '@clerk/react-router': 0.1.4
  '@cloudflare/workers-types': 4.20241218.0
  '@date-fns/tz': 1.2.0
  '@date-fns/utc': 2.1.0
  '@hono/node-server': 1.13.7
  '@hono/vite-build': 1.2.0
  '@hono/vite-dev-server': 0.17.0
  '@libsql/kysely-libsql': 0.4.1
  '@radix-ui/react-accordion': 1.2.2
  '@radix-ui/react-alert-dialog': 1.1.4
  '@radix-ui/react-aspect-ratio': 1.1.1
  '@radix-ui/react-avatar': 1.1.2
  '@radix-ui/react-checkbox': 1.1.3
  '@radix-ui/react-dialog': 1.1.4
  '@radix-ui/react-dropdown-menu': 2.1.4
  '@radix-ui/react-label': 2.1.1
  '@radix-ui/react-popover': 1.1.4
  '@radix-ui/react-select': 2.1.4
  '@radix-ui/react-separator': 1.1.1
  '@radix-ui/react-slot': 1.1.1
  '@radix-ui/react-switch': 1.1.2
  '@radix-ui/react-tabs': 1.1.2
  '@radix-ui/react-toggle': 1.1.1
  '@radix-ui/react-tooltip': 1.1.6
  '@react-router/cloudflare': 7.0.2
  '@react-router/dev': 7.0.2
  '@react-router/remix-routes-option-adapter': 7.0.2
  '@types/node': 22.10.2
  '@types/nprogress': 0.2.3
  '@types/react': 19.0.2
  '@types/react-dom': 19.0.2
  '@typescript-eslint/eslint-plugin': 6.7.4
  '@typescript-eslint/parser': 6.7.4
  autoprefixer: 10.4.20
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.0.4
  concurrently: 9.1.0
  date-fns: 4.1.0
  dotenv: 16.4.7
  fast-xml-parser: 4.5.1
  hono: 4.6.14
  isbot: 5.1.18
  kysely: 0.27.5
  lucide-react: 0.468.0
  next-themes: 0.4.4
  npm-run-all: 4.1.5
  nprogress: 0.2.0
  postcss: 8.4.49
  prettier: 3.4.2
  prettier-plugin-organize-imports: 4.1.0
  prettier-plugin-tailwindcss: 0.6.9
  prisma: 6.1.0
  prisma-kysely: 1.8.0
  react: 19.0.0
  react-dom: 19.0.0
  react-twc: 1.4.2
  react-router: 7.0.2
  recharts: 2.15.0
  remix-flat-routes: 0.6.5
  sonner: 1.7.1
  tailwind-merge: 2.5.5
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  tsx: 4.19.2
  turbo: 2.3.3
  typescript: 5.7.2
  vaul: 1.1.2
  vite: 5.4.11
  vite-tsconfig-paths: 5.1.4
  vitest: 2.1.8
  wrangler: 3.99.0
  zx: 8.2.4
