packages:
  - ./apps/*
  - ./packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@cloudflare/workers-types": 4.20241106.0
  "@google-cloud/bigquery": 7.9.1
  "@hono/node-server": 1.13.5
  "@hono/vite-build": 1.1.0
  "@hono/vite-dev-server": 0.16.0
  "@types/node": 22.9.0
  fast-xml-parser: 4.5.0
  hono: 4.6.9
  kysely: 0.27.4
  kysely-d1: 0.3.0
  npm-run-all: 4.1.5
  turbo: 2.2.3
  typescript: 5.6.3
  vite: 5.4.10
  vitest: 2.1.4
  wrangler: 3.86.0
