/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface AdEvents {
  adGroupId: string | null;
  adId: string | null;
  adSlotId: string | null;
  advertiserId: string | null;
  campaignId: string | null;
  eventTimestamp: Generated<string>;
  eventType: string;
  id: string;
  impressionId: string | null;
  ipAddress: string;
  mediaId: string | null;
  progress: number | null;
  uid: string;
  userAgent: string;
}

export interface AdGroups {
  advertiserId: string;
  bidPriceCpm: string;
  campaignId: string;
  categories: string | null;
  createdAt: Generated<string>;
  frequencyCapImpressions: number;
  frequencyCapUnit: string;
  frequencyCapWindow: number;
  id: string;
  name: string;
  updatedAt: Generated<string>;
}

export interface Ads {
  adGroupId: string;
  advertiserId: string;
  clickThroughUrl: string;
  createdAt: Generated<string>;
  description: string | null;
  duration: number;
  height: number | null;
  id: string;
  mimeType: string | null;
  type: string;
  updatedAt: Generated<string>;
  url: string;
  width: number | null;
}

export interface AdSlots {
  createdAt: Generated<string>;
  id: string;
  mediaId: string;
  name: string;
  type: string;
  updatedAt: Generated<string>;
}

export interface Advertisers {
  createdAt: Generated<string>;
  id: string;
  name: string;
  organizationId: string;
  updatedAt: Generated<string>;
}

export interface Campaigns {
  advertiserId: string;
  budget: Generated<string>;
  budgetType: string;
  createdAt: Generated<string>;
  deliveryPace: string;
  endAt: string;
  id: string;
  name: string;
  remainingBudget: Generated<string>;
  spentBudget: Generated<string>;
  startAt: string;
  status: Generated<string>;
  updatedAt: Generated<string>;
}

export interface Clicks {
  adGroupId: string;
  adId: string;
  adSlotId: string;
  advertiserId: string;
  campaignId: string;
  clickThroughUrl: string;
  createdAt: Generated<string>;
  id: string;
  impressionId: string;
  ipAddress: string;
  isCompanion: number;
  mediaId: string;
  timestamp: Generated<string>;
  uid: string;
  updatedAt: Generated<string>;
  userAgent: string;
}

export interface CompanionBanners {
  adId: string;
  clickThroughUrl: string | null;
  createdAt: Generated<string>;
  height: number;
  id: string;
  mimeType: string | null;
  updatedAt: Generated<string>;
  url: string;
  width: number;
}

export interface CompanionSlots {
  adSlotId: string;
  createdAt: Generated<string>;
  height: number;
  id: string;
  name: string;
  updatedAt: Generated<string>;
  width: number;
}

export interface DailyReports {
  adGroupId: string;
  adId: string;
  adSlotId: string;
  advertiserId: string;
  campaignId: string;
  clicks: Generated<number>;
  createdAt: Generated<string>;
  date: string;
  impressions: Generated<number>;
  mediaId: string;
  reach: Generated<number>;
  updatedAt: Generated<string>;
}

export interface Invitation {
  createdAt: string;
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Media {
  categories: string | null;
  createdAt: Generated<string>;
  id: string;
  name: string;
  organizationId: string;
  updatedAt: Generated<string>;
}

export interface Member {
  createdAt: string;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Organization {
  createdAt: string;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: string | null;
  banned: number | null;
  banReason: string | null;
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: string;
}

export interface Verification {
  createdAt: string;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string;
  value: string;
}

export interface DB {
  account: Account;
  adEvents: AdEvents;
  adGroups: AdGroups;
  ads: Ads;
  adSlots: AdSlots;
  advertisers: Advertisers;
  campaigns: Campaigns;
  clicks: Clicks;
  companionBanners: CompanionBanners;
  companionSlots: CompanionSlots;
  dailyReports: DailyReports;
  invitation: Invitation;
  media: Media;
  member: Member;
  organization: Organization;
  session: Session;
  user: User;
  verification: Verification;
}
