// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	TRACKER_ORIGIN: string;
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	TURSO_DATABASE_URL: string;
	TURSO_AUTH_TOKEN: string;
	ASSETS: Fetcher;
}
