name = "video-ad-network"
compatibility_date = "2024-09-25"
# compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./public", binding = "ASSETS" }

# [vars]
# MY_VAR = "my-variable"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "video-ad-network"
database_id = "ad4c0de9-dc9d-44b1-b2c2-e7f343cf2841"

[observability]
enabled = true

