name = "video-ad-network"
compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./public", binding = "ASSETS" }

[vars]
TRACKER_ORIGIN = "https://video-ad-network-tracker.fly.dev"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[observability]
enabled = true

