#:schema node_modules/wrangler/config-schema.json
name = "ad-server"
compatibility_date = "2024-09-26"
compatibility_flags = [ "nodejs_compat" ]
assets = { directory = "./public", binding = "ASSETS" }

[vars]
TRACKER_ORIGIN = "https://ad-server.van.techtalk.jp"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[observability]
enabled = true

